project:
  type: website

website:
  title: "Irina Kolbun"
  navbar:
    left:
      - href: index.qmd
        text: About me
      - projects.qmd
      - education.qmd

format:
  html:
    theme: lux
    css: styles.css
    toc: true

editor: visual

